name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
      - name: Build only (tests disabled temporarily)
        run: mvn clean package -DskipTests=true
      # - name: Run tests (disabled due to Java 24 + Mockito incompatibility)
      #   run: mvn test

# Para deploy automático a Render, Railway, Fly.io, puedes usar webhooks o su CLI en otro job. 